"""initial

Revision ID: d9144df95951
Revises: 
Create Date: 2026-03-17 21:07:37.165807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9144df95951'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receptores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('admin', 'registrador', 'recaudador', 'gestor', name='tipo_usuario_enum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False, comment='True cuando el Admin asignó contraseña temporal'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='accion_audit_enum'), nullable=False),
    sa.Column('campo_modificado', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fecha_accion', sa.DateTime(), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receptor_id', sa.UUID(), nullable=False),
    sa.Column('entidad_bancaria', sa.String(length=100), nullable=False),
    sa.Column('tipo_cuenta', sa.Enum('ahorros', 'corriente', name='tipo_cuenta_enum'), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['receptor_id'], ['receptores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gestores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=150), nullable=False),
    sa.Column('receptor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receptor_id'], ['receptores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo_electronico'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gestor_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=150), nullable=True),
    sa.Column('afiliacion_militar', sa.Boolean(), nullable=False),
    sa.Column('al_dia', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gestor_id'], ['gestores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('creditos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('numero_credito_cliente', sa.String(length=20), nullable=False, comment='Formato: {cedula_cliente}-CR-{secuencial:03d}'),
    sa.Column('tipo_credito', sa.Enum('cuota_fija', 'abono_capital', name='tipo_credito_enum'), nullable=False),
    sa.Column('capital_prestado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tasa_interes_mensual', sa.Numeric(precision=5, scale=4), nullable=False, comment='Ej: 0.0300 para 3% mensual'),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('fecha_inicial_pago', sa.Date(), nullable=False),
    sa.Column('periodicidad', sa.Enum('mensual', 'quincenal', 'semanal', 'diario', name='periodicidad_enum'), nullable=False),
    sa.Column('saldo_capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_intereses', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('abono_minimo', sa.Numeric(precision=15, scale=2), nullable=True, comment='Solo para abono_capital'),
    sa.Column('numero_cuotas', sa.Integer(), nullable=True, comment='Requerido para cuota_fija. NULL para abono_capital'),
    sa.Column('calcular_interes_dias_corridos', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_credito_cliente')
    )
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credito_id', sa.UUID(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('tipo_cuota', sa.Enum('programada', 'no_programada', 'interes', 'abono', name='tipo_cuota_enum'), nullable=False),
    sa.Column('monto_a_pagar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('capital_a_pagar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interes_a_pagar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('capital_pagado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interes_pagado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('momento', sa.String(length=5), nullable=False),
    sa.Column('fecha_maxima', sa.Date(), nullable=False),
    sa.Column('receptor_id', sa.UUID(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('validado_recaudador', sa.Boolean(), nullable=False),
    sa.Column('fecha_pago_real', sa.Date(), nullable=True),
    sa.Column('es_excedente_a', sa.Enum('capital', 'intereses', name='destino_excedente_enum'), nullable=True),
    sa.Column('es_ultimo_pago', sa.Boolean(), nullable=False, comment='True cuando es la última cuota de un crédito cuota_fija'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['receptores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('creditos')
    op.drop_table('clientes')
    op.drop_table('gestores')
    op.drop_table('cuentas_bancarias')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('receptores')
    # ### end Alembic commands ###
